---
title: "Abschluss- und Projektarbeiten"
date: today
date-format: "DD.MM.YYYY"
---

Hier finden Sie eine Übersicht der aktuellen Abschluss- und Projektarbeiten des Labors für Mobile Robotik der TH Nürnberg

Soweit nicht anders angegeben, können alle Themen als Bachelor- oder Masterarbeit bearbeitet werden, sowie als Projektarbeit.

## Offene Themen

| Titel | Betreuer | Link |
|-------|----------|------|
| Autonomous Paradrone | Prof. Dr. Enrico Schröder | [PDF](build/2026_06_autonomous_paradrone.pdf) |
| AI-based Processing of Traffic Monitoring Footage | Prof. Dr. Enrico Schröder | [PDF](build/2026_06_traffic_monitoring.pdf) |
| Robocup Smart Manufacturing League (SML) | Prof. Dr. Enrico Schröder | [PDF](build/2026_06_smart_manufacturing_applications.pdf) |
| Intelligenter Begleitroboter für das Klinikum Nürnberg | Prof. Dr. Stefan May | [PDF](build/2025_06_patientenassistenz.pdf) |
| Drone Charging Setup | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_crazyflies_charging_en.pdf) |
| Drone Light Painting | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_crazyflies_light_painting_en.pdf) |
| Fallstudie Technologien in Unternehmen (TTZ) | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_ttz_fallstudie_robotik_en.pdf) |
| 2R-Roboterarm: Gravity Compensation & Reinforcement Learning | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_2r_roboterarm_en.pdf) |
| M-APR: Emergente Systeme in der Produktion (TTZ) | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_mapr_emergente_systeme_en.pdf) |
| M-APR: Handling flexibler Materialien (TTZ) | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_mapr_flexible_materialien_en.pdf) |
| Mini-Roboter mit Mecanum-Antrieb | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_mini_roboter_mecanum_en.pdf) |
| <s>Erkennung von Objekten mittels Semantischer Segmentierung</s> (in Bearbeitung) | Prof. Dr. Enrico Schröder | [PDF](build/2025_03_semseg.pdf) |
| <s>Greifen von Objekten mittels Reinforcement Learning</s> (in Bearbeitung) | Prof. Dr. Enrico Schröder | [PDF](build/2025_03_rl_grasping.pdf) |
| <s>Markerlose Indoor-Lokalisierung einer Drohne </s> (in Bearbeitung) | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_drohne_indoor_lokalisierung_en.pdf) |
| <s>Drone Swarm Obstacle Avoidance </s> (in Bearbeitung) | Prof. Dr. Christian Pfitzner | [PDF](build/2026_06_crazyflies_obstacle_swarm_en.pdf) |

